name: Add single mod and all dependencies

on:
  workflow_dispatch:
    inputs:
      modid_projectid:
        description: 'Write projetcId of mod'
        required: true
        default: '876781'
        type: string
      fileid: 
        description: 'Write modId of mod'
        required: true
        default: '5397482'
        type: string
env:
  BASE_URL: https://api.curseforge.com
  MAX_PAGE_SIZE: 50
  API_KEY: \$2a\$10\$4UughKvVMNC9Yl0cUfhAsOiOkCWgy/k/6rn.z5bIztd62LpZ1eibe

jobs:
  download_and_install_mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DO_DROPLET }}

      - name: Create environment file
        run: |
          INPUT_MOD_ID=${{ github.event.inputs.modid_projectid }}
          INPUT_FILE_ID=${{ github.event.inputs.fileid }}
          echo "BASE_URL=$BASE_URL" > .env
          echo "API_KEY=$API_KEY" >> .env
          echo "INPUT_MOD_ID=$INPUT_MOD_ID" >> .env
          echo "INPUT_FILE_ID=$INPUT_FILE_ID" >> .env
          cat .env  # Debug to ensure the file is correct

      - name: Copy .env file to Droplet
        run: |
          scp -o StrictHostKeyChecking=no .env root@206.189.84.101:/root/tempMC/

      - name: Copy files from push to droplet and start from the new version
        run: |
         ssh -o StrictHostKeyChecking=no root@206.189.84.101 <<'EOF'
          source /root/tempMC/.env
          echo "Running commands on the Droplet"
          echo "Base URL: $BASE_URL"
          echo "API_KEY: $API_KEY"
          echo "MAX_PAGE_SIZE: $MAX_PAGE_SIZE"
          echo "INPUT_MOD_ID: $INPUT_MOD_ID"
          cd /root/tempMC
            
          api_url="$BASE_URL/v1/mods/$INPUT_MOD_ID/files/$INPUT_FILE_ID/download-url"
          api_url2="$BASE_URL/v1/mods/$INPUT_MOD_ID/files/$INPUT_FILE_ID"
          echo "API URL: $api_url"
            
          # Fetch the download URL using curl and jq
          response=$(curl -vvv "$api_url" -H "Host: api.curseforge.com" -H "Range: bytes=0-7000000" -H "x-api-key: $API_KEY" -H "User-Agent: GitHubActionsRunner/1.0" -H "Accept: */*" -H "Cache-Control: no-cache" | jq -r '.data')
          echo "Extracted response: $response2"
          
          # Extract download URL
          downloadUrl=$(echo $response | jq -r '.data')
            
          # Debug: Output the extracted URL
          echo "Extracted URL: $downloadUrl"
            
          # Validate the URL format
          if [[ $downloadUrl =~ ^https?:// ]]; then
            echo "Valid URL: $downloadUrl"
              
             # Download the file using the obtained URL
            curl -O "$downloadUrl"
           else
            echo "Invalid URL extracted: $downloadUrl"
            exit 1
          fi

          echo "Install deps" 
          getInfoAboutMod=$(curl --location "$api_url2" --header "Range: bytes=0-7000000" --header "x-api-key: $API_KEY")
          echo "Extracted getInfoAboutMod: $getInfoAboutMod"
          
         EOF

    
