name: Use Uploaded File Artifact

on:
  workflow_run:
    workflows: ["Upload File Artifact"]
    types:
      - completed

jobs:
  use-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download user-uploaded file
      uses: actions/download-artifact@v2
      with:
        name: user-uploaded-file
        path: ./downloaded

    - name: Display file contents
      run: cat ./downloaded/path/to/local/file  # Update this path based on where the file was downloaded to

    - name: Execute SSH commands
      run: |
        ssh -o StrictHostKeyChecking=no root@206.189.84.101 <<'EOF'
          cat > /root/received_user_file.txt << 'END_OF_FILE'
          $(cat ./downloaded/path/to/local/file)  # Update this path based on where the file was downloaded to
          END_OF_FILE
          echo "File received on server:"
          cat /root/received_user_file.txt
        EOF
