name: Add single mod and all dependencies or modpack

on:
  workflow_dispatch:
    inputs:
      projectid:
        description: 'Write projetcId of mod'
        required: true
        default: '431168' 
        type: string
      fileid: 
        description: 'Write modId of mod'
        required: true
        default: '5011582'
        type: string
      excluded_mods: 
        description: 'Write modId of mod that should be excluded (1, 2, 3 input format)'
        required: false
        default: '245506,298744,298965,231868,64578,261199,407657,407632'
        type: string
      start_server: 
        description: 'Start server after installation?'
        required: false
        default: false 
        type: boolean
env:
  BASE_URL: https://api.curseforge.com
  WORK_PATH: /root/temp
  SERVER_PATH: /root/main
  MAX_PAGE_SIZE: 50
  API_KEY: \$2a\$10\$4UughKvVMNC9Yl0cUfhAsOiOkCWgy/k/6rn.z5bIztd62LpZ1eibe

jobs:
  download_and_install_mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DO_DROPLET }}

      - name: Create environment file
        run: |
          INPUT_PROJECT_ID=${{ github.event.inputs.projectid }}
          INPUT_FILE_ID=${{ github.event.inputs.fileid }}
          INPUT_EXLUDED_MODS=${{ github.event.inputs.excluded_mods }}
          echo "BASE_URL=$BASE_URL" > .env
          echo "WORK_PATH=$WORK_PATH" >> .env
          echo "SERVER_PATH=$SERVER_PATH" >> .env
          echo "API_KEY=$API_KEY" >> .env
          echo "MAX_PAGE_SIZE=$MAX_PAGE_SIZE" >> .env
          echo "INPUT_PROJECT_ID=$INPUT_PROJECT_ID" >> .env
          echo "INPUT_FILE_ID=$INPUT_FILE_ID" >> .env
          echo "INPUT_EXLUDED_MODS=$INPUT_EXLUDED_MODS" >> .env
          cat .env  

      - name: Copy .env file to Droplet
        run: |
          scp -o StrictHostKeyChecking=no .env root@206.189.84.101:/root/

      - name: Fetch main mod and recursive fetch deps
        run: |
         ssh -o StrictHostKeyChecking=no root@206.189.84.101 <<'EOF'
           is_excluded_mod() {
              local projectId=$1
              for excluded_mod in "${excluded_mods_array[@]}"; do
                if [[ "$projectId" == "$excluded_mod" ]]; then
                  return 0
                fi
              done
              return 1
          }
          fetch_with_dlink() {
            local url=$1

            downloadUrl=$(curl "$url" -H "x-api-key: $API_KEY" | sed '/HTTP_STATUS:/d' | jq -r '.data')
            echo "Extracted URL: $downloadUrl"

            fileName=$(basename "$downloadUrl")
            echo "fileName: $fileName"
          
            if [[ $downloadUrl =~ ^https?:// ]]; then
              echo "Valid URL: $downloadUrl"
              serverModPath="$WORK_PATH/$fileName"
         
              echo "Downloading mod for server: $downloadUrl $serverModPath"
              curl -o "$serverModPath" -L "$downloadUrl"
            else
              echo "Invalid URL extracted: $downloadUrl"
              exit 1
            fi
          }
          process_dependency() {
            local dep=$1
            local gameVersionFromMainMod=$2

              echo "Downloading dep: $dep"
              forgeGameVersion="Forge"
              serverGameVersion="Server"
              modId=$(echo "$dep" | jq -r '.modId')
              if is_excluded_mod "$projectID"; then
                 echo "Skipping excluded mod: $projectID"
              else
                relationType=$(echo "$dep" | jq -r '.relationType')
                api_url_mod_files="$BASE_URL/v1/mods/$modId/files"

                touch "$WORK_PATH"/response_dep.json
                curl -L "$api_url_mod_files" -H "x-api-key: $API_KEY" -o "$WORK_PATH"/response_dep.json

                echo "Checking for compatible dependency"

                jq -c -r '.data[]' "$WORK_PATH"/response_dep.json | while IFS= read -r versionInfo; do
                  if echo "$versionInfo" | jq -e  --arg gameVersion "$versionInfo" '.gameVersions | index($gameVersion)' >/dev/null; then
                    download_link=$(echo "$versionInfo" | jq -r ".downloadUrl")
                    fetch_with_dlink "$download_link"
                    
                    echo "Checking for inner deps and install if needed"
                    has_req_inner_deps=$(echo "$versionInfo" | jq -r '[.dependencies[] | select(.relationType == 3)] |  length')
                    if [ "$has_req_inner_deps" -gt 0 ]; then
                      echo "Mod with inner deps: $versionInfo"
                      deps=$(echo "$versionInfo" | jq -r "[.dependencies[] | select(.relationType == 3)]")

                      echo "Inner req deps: $deps"
                      echo "$deps" | jq -c '.[]' | while IFS= read -r dep; do
                        process_dependency "$dep" "$gameVersionFromMainMod"
                      done
                    else
                      echo "There IS NO inner deps"
                    fi
                  else
                      echo "Not suitable version"
                  fi
                done
              fi
          }
          source /root/.env
          IFS=',' read -r -a excluded_mods_array <<< "$INPUT_EXLUDED_MODS"
          
          cd "$SERVER_PATH"
            
          api_url_dlink="$BASE_URL/v1/mods/$INPUT_PROJECT_ID/files/$INPUT_FILE_ID/download-url"
          api_url_info="$BASE_URL/v1/mods/$INPUT_PROJECT_ID/files/$INPUT_FILE_ID"

          fetch_with_dlink "$api_url_dlink" false

          echo "Install deps if needed"
          touch "$WORK_PATH"/response.json
          curl -L "$api_url_info" -H "x-api-key: $API_KEY" -o "$WORK_PATH"/response.json

          if [[ -s "$WORK_PATH"/response.json ]]; then
            echo "Successfully downloaded response.json"
            has_dependencies=$(jq -r '.data.dependencies | length' "$WORK_PATH"/response.json)
            echo "Has Deps? $has_dependencies"
            
            if [ "$has_dependencies" -gt 0 ]; then
              dep_lvl_req=3
              # dep_lvl_opt=2
              deps=$(jq --argjson dep_lvl_req "$dep_lvl_req" --argjson dep_lvl_opt "$dep_lvl_opt" -r '[.data.dependencies[] | select(.relationType == $dep_lvl_req or .relationType == $dep_lvl_opt)]' "$WORK_PATH"/response.json )
              gameVersion=$(jq -r '.data.gameVersions[] | select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))' "$WORK_PATH"/response.json)
              echo "Dependencies list: $deps"

              echo "$deps" | jq -c '.[]' | while IFS= read -r dep; do
                process_dependency "$dep" "$gameVersion"
              done
            else
              echo "Has no deps in mod"
            fi
          else
            echo "No information on deps"
          fi
         EOF

      - name: Install all modes from temp and clear temp
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 <<'EOF'
            is_excluded_mod() {
              local projectId=$1
              for excluded_mod in "${excluded_mods_array[@]}"; do
                if [[ "$projectId" == "$excluded_mod" ]]; then
                  return 0
                fi
              done
              return 1
            }
            fetch_with_dlink() {
              local url=$1
      
              downloadUrl=$(curl "$url" -H "x-api-key: $API_KEY" | sed '/HTTP_STATUS:/d' | jq -r '.data')
              echo "Extracted URL: $downloadUrl"

              fileName=$(basename "$downloadUrl")
              echo "fileName: $fileName"
              
              if [[ $downloadUrl =~ ^https?:// ]]; then
                echo "Valid URL: $downloadUrl"
                serverModPath="$SERVER_PATH/mods/$fileName"
                echo "Downloading mod for server: $downloadUrl $serverModPath"
                curl -o "$serverModPath" -L "$downloadUrl"
              else
                echo "$projectID" >> "$notAccessibleModsFile"
                echo "Some mod cannot be added $projectID. Current list: $(cat $notAccessibleModsFile)"
              fi
            }
            source /root/.env
            IFS=',' read -r -a excluded_mods_array <<< "$INPUT_EXLUDED_MODS"

            api_url_dlink="$BASE_URL/v1/mods/$INPUT_PROJECT_ID/files/$INPUT_FILE_ID/download-url"
            notAccessibleModsFile="$WORKING_PATH"/notAccessible.txt
            > "$notAccessibleModsFile"
            cd "$WORK_PATH"
    
            for file in *.zip; do
              if [ -f "$file" ]; then
                echo "Found archive in folder, trying to unpack and install"
                unzip -o "$file"

                cp -r "$WORK_PATH"/overrides/* "$SERVER_PATH"
                
                echo "Trying to find manifest.json after unzipping"
                if [[ -f "$WORK_PATH"/manifest.json ]]; then 
                  echo "There is manifest.json"
                  cat ./manifest.json | jq -c '.files[]' | while IFS= read -r mod ; do
                    echo "$mod"
                    projectID=$(echo "$mod" | jq '.projectID')
                    fileId=$(echo "$mod" | jq '.fileID')
                    dyn_api_url="$BASE_URL/v1/mods/$projectID/files/$fileId/download-url"

                    if is_excluded_mod "$projectID"; then 
                      echo "Excluded mod. Skipping installation"
                    else 
                      fetch_with_dlink "$dyn_api_url"
                    fi
                  done
                else
                  echo "There is no manifest.json in modpack"
                fi
              else
               echo "There is no modpack file"
              fi
            done 

            for file in *.jar; do 
              cp "$WORK_PATH"/"$file" "$SERVER_PATH"/mods
            done
            
            echo "There are some mods that cannot be downloaded via API, download them manually. List of mods: $(cat $notAccessibleModsFile)"
            rm -r "$WORK_PATH"/*
          EOF
