name: Fetch from latest

on:
  workflow_dispatch:
    inputs:
      is_rebase:
        description: 'Rebase on main?'
        required: false
        default: false
        type: boolean
      is_installator:
        description: 'Is file on git an installer?'
        required: false
        type: boolean
        default: false
      start_server:
        description: 'Start server?'
        required: false
        default: false
        type: boolean
      is_reset:
        description: 'Reset files to last branch?'
        required: false
        default: false
        type: boolean

jobs:
  fetch_files_from_latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DO_DROPLET }}

      - name: Pull from main
        if: ${{ github.event.inputs.is_rebase == 'false' }}
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/main
            remote_repo="https://Animels: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@github.com/Animels/minecraft-actions.git"

            git add .
            git commit -m "Committed before pull"
            git pull "$remote_repo" main --no-ff
          EOF

      - name: Rebase on main
        if: ${{ github.event.inputs.is_rebase == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/main
            remote_repo="https://Animels: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@github.com/Animels/minecraft-actions.git"
            
            git add .
            git commit -m "Committed before rebase"
            git rebase main
            git rebase --skip
          EOF

      - name: Reset on last branch
        if: ${{ github.event.inputs.is_reset == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/main
            git reset main/main --hard           
          EOF

      - name: Start installation if installer
        if: ${{ github.event.inputs.is_installator == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/main
            installationFile=$(find forge*installer.jar)
            echo "installationFile: $installationFile"

            java -jar ./"$installationFile" --installServer
            echo "eula=true" > eula.txt
            rm ./"$installationFile"*
          EOF
          

      - name: Killing prev and start server
        if: ${{ github.event.inputs.start_server == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/main

            echo "Killing any existing java process"
            existing_pid=$(ps -e | grep java | awk '{print $1}')
            kill -9 "$existing_pid"

            echo "Starting server"
            FILE=$(ls forge* | head -n 1)
            chmod 7 ./$FILE
            nohup java -jar ./$FILE &

            PID=$(ps -e | grep java | awk '{print $1}')
            WAIT_TIME=60

            echo "Spying on process"
            for ((i = 0 ; i < WAIT_TIME ; i++)); do
              if ps -p $PID > /dev/null; then
                sleep 1
              else
                exit 1
              fi
            done
            echo "Server Process($PID) is still running after $WAIT_TIME seconds"
          EOF

          
          
