name: Fetch from latest

on:
  workflow_dispatch:
    inputs:
      is_rebase:
        description: 'Rebase on main?'
        required: false
        default: false
        type: boolean
      is_installator:
        description: 'Is file on git an installer?'
        required: false
        type: boolean
        default: false
      start_server:
        description: 'Start server?'
        required: false
        default: false
        type: boolean

jobs:
  fetch_files_from_latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DO_DROPLET }}

      - name: Pull from main
        if: ${{ github.event.inputs.is_rebase == 'false' }}
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/main
            remote_repo="https://Animels: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@github.com/Animels/minecraft-actions.git"

            git add .
            git commit -m "Committed before pull"
            git pull "$remote_repo" main --no-ff
          EOF

      - name: Rebase on main
        if: ${{ github.event.inputs.is_rebase == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/main
            remote_repo="https://Animels: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@github.com/Animels/minecraft-actions.git"
            
            git add .
            git commit -m "Committed before rebase"
            git rebase main
            git rebase --skip
          EOF

      - name: Start installation if installer
        if: ${{ github.event.inputs.is_installator }}
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/main
            installationFile=$(find forge*installer.jar)
            echo "installationFile: $installationFile"

            java -jar ./"$file" --installServer

            mcServerFile=$(find minecraft_server*.jar)
            echo "mcServerFile: $mcServerFile"
            java -jar ./"$mcServerFile"

            echo "eula=true" > eula.txt

            rm ./"$installationFile"
          EOF
          

      - name: Start server
        if: ${{ github.event.inputs.start_server }}
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/main
            FILE=$(ls forge* | head -n 1)
            chmod 7 ./$FILE
            java -jar ./$FILE

            PID=$(cat process_id.txt)
            WAIT_TIME=60

            for ((i = 0 ; i < WAIT_TIME ; i++)); do
              if ps -p $PID > /dev/null; then
                cp -r /root/tempMC/* /root/mainMC/
                sleep 1
              else
                cat /root/tempMC/logs/latest.log
                exit 1
              fi
            done
            echo "Server Process is still running after $WAIT_TIME seconds"
          EOF

          
          
