name: Connect to Droplet

on:
  push:
    branches:
      - main

env:
  DAY_OF_WEEK: Monday

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DO_DROPLET }}

      - name: Copy files from push to droplet and start from the new version
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/tempMC
            git pull origin main
            FILE=$(ls forge* | head -n 1)
            chmod 7 ./$FILE
            java -jar ./$FILE
          EOF
          
          
