name: Connect to Droplet

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Update whole server files'
        required: false
        type: boolean

jobs:
  start_server_from_latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DO_DROPLET }}

      - name: Copy files from push to droplet and start from the new version
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/tempMC
            git pull origin main
            FILE=$(ls forge* | head -n 1)
            chmod 7 ./$FILE
            java -jar ./$FILE
          EOF

      - name: Wait and check process
        run: |
          # Read the process ID
          PID=$(cat process_id.txt)

          # Duration to wait (in seconds)
          WAIT_TIME=60

          # Wait for the specified duration and check if the process is still running
          for ((i = 0 ; i < WAIT_TIME ; i++)); do
            if ps -p $PID > /dev/null; then
              cp -r /root/tempMC/* /root/mainMC/
              sleep 1
            else
              cat /root/tempMC/logs/latest.log
              exit 1
            fi
          done

          echo "Server Process is still running after $WAIT_TIME seconds"
          
          
          
