name: Makes branch(version) from current server state

on: 
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Make shure version '
        required: true
        default: ''
        type: string

env:
  BASE_URL: https://api.curseforge.com
  SSH_AUTH: root@206.189.84.101

jobs: 
  makes_version: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DO_DROPLET }}

      - name: Create environment file
        run: |
          VERSION_NAME=${{ github.event.inputs.version_name }}
          echo "VERSION_NAME=$VERSION_NAME" > .env
          cat .env  

      - name: Copy .env file to Droplet
        run: |
          scp -o StrictHostKeyChecking=no .env "$SSH_AUTH":/root/

      - name: Make new branch and version
        run: |
          ssh -o StrictHostKeyChecking=no "$SSH_AUTH" << 'EOF'
            echo "Running commands on the Droplet"
            source /root/.env
            cd /root/main
            remote_repo="https://Animels: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@github.com/Animels/minecraft-actions.git"

            git branch "$VERSION_NAME"
            git checkout "$VERSION_NAME" 
            
            git add .
            git commit -m "Committed before pull"
            git push "$remote_repo"
          EOF
