name: Removes files according to path

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to file or folder'
        required: true
        default: '/root/'
        type: string

jobs:
  purge_path:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up SSH agent
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SSH_DO_DROPLET }}

        - name: Create environment file
          run: |
            INPUT_PATH=${{ github.event.input.path}}
            echo "INPUT_PATH=$INPUT_PATH"
            echo "INPUT_PATH=$INPUT_PATH" > .env
            cat .env  

        - name: Copy .env file to Droplet
          run: |
            scp -o StrictHostKeyChecking=no .env root@206.189.84.101:/root/tempMC/
  
        - name: Purge files from /root
          run: |
            ssh -o StrictHostKeyChecking=no root@206.189.84.101 <<'EOF'
                source /root/tempMC/.env
                echo "INPUT_PATH=$INPUT_PATH"
                rm -r "$INPUT_PATH"
            EOF
          
