name: Push server files to git

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Pushes server files to git'
        required: true
        type: boolean

env: 
  SSH_AUTH: root@206.189.84.101

jobs:
  purge_path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DO_DROPLET }}

      - name: Addinf, committing, pushing
        run: |
          ssh -o StrictHostKeyChecking=no "$SSH_AUTH" <<'EOF'
            cd /root/main
            remote_repo="https://Animels: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@github.com/Animels/minecraft-actions.git"

            
            git pull "$remote_repo"
            git merge "$remote_repo" --no-ff --strategy-option theirs

            git add .
            git commit -a -m "Pushing from server"
            git push "$remote_repo"
          EOF
