name: Copy files from main branch and start forge

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Update whole server files'
        required: false
        type: boolean

jobs:
  start_server_from_latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DO_DROPLET }}

      - name: Copy files from main branch and start forge
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            echo "Running commands on the Droplet"
            cd /root/tempMC
            git pull
            FILE=$(ls forge* | head -n 1)
            chmod 7 ./$FILE
            java -jar ./$FILE
          EOF

      - name: Wait and check process
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.84.101 << 'EOF'
            PID=$(cat process_id.txt)
            WAIT_TIME=60

            for ((i = 0 ; i < WAIT_TIME ; i++)); do
              if ps -p $PID > /dev/null; then
                cp -r /root/tempMC/* /root/mainMC/
                sleep 1
              else
                cat /root/tempMC/logs/latest.log
                exit 1
              fi
            done

            echo "Server Process is still running after $WAIT_TIME seconds"
          EOF

    
          
          
          
          
